// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJsIObIy9l_hpxZukw2edj95llpO_XnA',
    appId: '1:245175183655:web:fa40a1a3b91611b266e102',
    messagingSenderId: '245175183655',
    projectId: 'commodity-trading-ebfcd',
    authDomain: 'commodity-trading-ebfcd.firebaseapp.com',
    storageBucket: 'commodity-trading-ebfcd.appspot.com',
    measurementId: 'G-046Z2LNEVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrJY1eg9b0ha094VcZ_l8UtZrjqSuMTtE',
    appId: '1:245175183655:android:39a364442354768066e102',
    messagingSenderId: '245175183655',
    projectId: 'commodity-trading-ebfcd',
    storageBucket: 'commodity-trading-ebfcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDHMcL17pKqILlEkDWZBzSDUJmiKBS7g',
    appId: '1:245175183655:ios:0e998aaec00d2d3066e102',
    messagingSenderId: '245175183655',
    projectId: 'commodity-trading-ebfcd',
    storageBucket: 'commodity-trading-ebfcd.appspot.com',
    iosBundleId: 'com.example.material3App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDHMcL17pKqILlEkDWZBzSDUJmiKBS7g',
    appId: '1:245175183655:ios:4a1c6bae07ab9a7b66e102',
    messagingSenderId: '245175183655',
    projectId: 'commodity-trading-ebfcd',
    storageBucket: 'commodity-trading-ebfcd.appspot.com',
    iosBundleId: 'com.example.material3App.RunnerTests',
  );
}
